name: C/C++ CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install build tools
        run: |
          if [[ $RUNNER_OS == 'Linux' ]]; then
            sudo apt-get update && sudo apt-get install -y build-essential;
          elif [[ $RUNNER_OS == 'macOS' ]]; then
            brew update && brew install gcc;
          fi

      - name: Compile C program
        run: |
          gcc -o program_name source_file.c


      - name: Run the compiled program
        run: ./program_name

